### ISSUE TITLE
no longer builds with libxcb-1.12

### ISSUE THREAD

**Issue by obadz** [stapelberg/X11-XCB#1]
(affects both 0.14 and 0.15)

See downstream: https://github.com/NixOS/nixpkgs/issues/15771

**Comment by vcunat** [comment]
I also filed https://rt.cpan.org/Public/Bug/Display.html?id=114732 but here might be a better place.

**Comment by stapelberg** [comment]
I saw both reports. I prefer interacting with GitHub because RT is so awkward.

With the old xcb-proto/libxcb, the signature looked like this:
```
HV *
create_gc(conn,cid,drawable,value_mask,value_list,...)
```
Whereas the new version looks like this:
```
HV *
create_gc(conn,cid,drawable,value_mask,function,plane_mask,foreground,background,line_width,line_style,cap_style,join_style,fill_style,fill_rule,tile,stipple,tile_stipple_x_origin,tile_stipple_y_origin,font,subwindow_mode,graphics_exposures,clip_x_origin,clip_y_origin,clip_mask,dash_offset,dashes,arc_mode)
```

**Comment by stapelberg** [comment]
https://cgit.freedesktop.org/xcb/proto/commit/?id=a3da4e8c60b5f6d2d3901f541561ead0adcad4b0 is the commit which broke X11::XCB.

**Comment by stapelberg** [comment]
Can someone confirm that commit ca512f6494f8b01d3dd8fb794ac95933aebba9c9 indeed fixes the issue? If yes, I’ll release a new version.

**Comment by vcunat** [comment]
Yes, picking that commit fixes compilation, including dependent i3.

**Comment by vcunat** [comment]
Thanks. Can you ping NixOS/nixpkgs#15771 after you make a release?

**Comment by stapelberg** [comment]
X11::XCB 0.16 was just released with the fix.

**Comment by obadz** [comment]
@stapelberg, thanks a lot for the quick turnaround!
